services:
#    product.example:
#        class: ProductBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    admin.product:
        class: ProductBundle\Admin\ProductAdmin
        arguments: [~, ProductBundle\Entity\Product, ~]
        tags:
           - { name: sonata.admin, manager_type: orm, label: Produit }
        public: true